---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ${params.name}
  namespace: ${namespaceName}
spec:
  replicas: 1
  selector:
    app: ${params.name}
    deploymentConfig: ${params.name}
  template:
    metadata:
      labels:
        namespace: ${namespaceName}
        app: ${params.name}
    spec:
      containers:
      - name: ${params.name}
        image: ${params.name}:${appTag}
        ports:
        - containerPort: 8763
      imagePullPolicy: IfNotPresent
  strategy:
    type: Rolling
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: ${params.name}
  labels:
    app: ${params.name}
    deploymentConfig: ${params.name}
spec:
  type: NodePort
  ports:
  - port: 8763
    targetPort: 8763
  selector:
    app: ${params.name}
---
